### ISSUE TITLE
Additional directory when setting path, starting with "/" in s3-compatible storages

### ISSUE THREAD

**Issue by berzerk54** [nixys/nxs-backup#30]
Greetings, collegues.

When setting up nxs-backup to collect backups in a s3-compatible storage, if you specify the path for collecting backups with / at the beginning (for example /nxs-backup/dump), then an empty directory "/" is created, which contains the "nxs-backup" directory.

The current solution to the problem is to specify the path without the "/" at the beginning. In this case, the correct nxs-backup directory with subdirectories is created.

**Comment by randreev1321** [comment]
Hi, @berzerk54.

Thanks for your interest in nxs-backup.

Indeed, this is an incorrect behavior. A fix has been added to PR #32 and will be released in an upcoming release.

**Comment by randreev1321** [comment]
Hi, @berzerk54 .

The release [v3.3.0](https://github.com/nixys/nxs-backup/releases/tag/v3.3.0) is out.

Pay attention. If your backups path in bucket starts with “/” (e.g.: //backups/…), you will need to move or delete old backups by yourself. Otherwise, everything should work correctly.

We look forward to receiving new requests.
