### ISSUE TITLE
Failed to delete file - directory not empty

### ISSUE THREAD

**Issue by Rawiiw** [nixys/nxs-backup#76]
Hi!

Nxs-backup sends an error that it cannot delete a directory because it is not empty. There is another directory inside. 
 
`[ERROR]: Server: ServerName: ServerName-desc-files Storage: local Message: Failed to delete file '/var/backups/files/desc/dump/dd/daily/var' with next error: remove /var/backups/files/desc/dump/dd/daily/var: directory not empty
`

Version: 3.9.0

**Comment by randreev1321** [comment]
Hi, @Rawiiw.

In a normal situation, there should be no third-party files and directories in the backup directory, otherwise they will be subject to rotation. As a solution to your case we added directory handling, a warning message will be returned to you asking you to remove the extraneous directory.

This has been fixed and released as part of the [v3.11.0](https://github.com/nixys/nxs-backup/releases/tag/v3.11.0) release.

New ideas and suggestions are welcome.
